### ISSUE TITLE
Babel plugin support?

### ISSUE THREAD

**Issue by graysonwright** [babel/ruby-babel-transpiler#286] opened 2015-11-23 10:46 UTC
Hello! I'm trying out [Flow](flowtype.org) on my Rails app, and I'm trying to set up `ruby-babel-transpiler` to strip out Flow type annotations.

There's [an existing Babel plugin](http://babeljs.io/docs/plugins/transform-flow-strip-types/) that can take care of this, but it doesn't look like it's available in `ruby-babel-transpiler`.

I've added this configuration to my `config/application.rb` file:

```ruby
    config.react.jsx_transform_options = {
      "plugins" => ["transform-flow-strip-types"],
    }
```

And in the browser, I get an error:
```
ReferenceError: Unknown plugin "transform-flow-strip-types"
```

I'm curious - is there a plan to make babel plugins available through this project? Would they be packaged as separate gems? If so, what would the structure of those gems look like?

**Comment by ralekna** [comment] 2015-11-23 13:53
As far as I know Babel automatically strips Flow annotations itself during transpilation and it doesn't need additional plugin for that. Have in mind that Flow is just a static type checker and doesn't add any code transformations and is more a code documentation tool.

**Comment by graysonwright** [comment] 2015-11-23 21:38
@ralekna thanks for the fast response!

According to [Flow's documentation](http://flowtype.org/docs/running.html), a special plugin is needed to strip out Flow annotations. I've tried using Flow in my Rails project without the plugin, and I got syntax errors that prevented the JS on the page from running.

[The bottom section of this page](http://flowtype.org/docs/running.html#transpiler-in-action) shows what the flow plugin is doing when it transforms the input.

**Comment by hzoo** [comment] 2015-11-23 22:32
The http://babeljs.io/docs/plugins/transform-flow-strip-types/ plugin is for babel 6 which has no plugins by default thus everything is opt-in.

**Comment by ralekna** [comment] 2015-11-24 02:42
@graysonwright it's a bit strange because as I see a PR for Babel v.6 (https://github.com/babel/ruby-babel-transpiler/pull/282) is not yet merged into master. Are you really sure that those syntax errors are cause by Flow markup? I use current version of this gem with Flow annotations and it works like a charm without adding any plugins.

**Comment by c-lliope** [comment] 2016-03-07 18:30
@ralekna - sorry for letting this get stale. I no longer have access to the app, so I'm not able to reproduce. It seems like it's working well for everyone else, so I'm OK closing this.

Thanks for your help!

**Closed by c-lliope** 2016-03-07 18:30 UTC

**Comment by selvagsz** [comment] 2018-05-03 08:36
Getting the same error while using  `transform-decorators` plugin. Are there any plans to merge the  babel v6 PR ?
